config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  resources :actors
end

app/models/actor.rb
class Actor < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/actors_controller.rb
class ActorsController < ActionController::Base
  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find_by_id(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  def home
    @actor = "Russel Bleiler"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/index.html.erb
<h1>Here are all my actors:</h1>

<% @actors.each do |actor| %>
  <p><%= link_to actor.first_name + ' ' + actor.last_name, actor_path(actor) %></p>
  <%= image_tag actor.profile_pic, style: 'width: 150px' %>
<% end %>

<%= link_to 'Go Home', root_path %>

app/views/actors/show.html.erb
<h1><%= @actor.first_name + ' ' + @actor.last_name %></h1>

<% if @actor.profile_pic.present? %>
  <%= image_tag @actor.profile_pic, style: 'width: 50%'  %>
<% else %>
  <p>no profile pic</p>
<% end%>
<br>

<%= link_to 'back to actors', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AliceGray</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>hello world!</h1>
<h2>a little smaller</h2>

<p>I am <%= @actor %> ... hear me <strong>roar!</strong></p>

<p><%= link_to 'Come see my gay actors', actors_path %></p>